# Pandas and dataframes
- **series** is a named and indexed column with data
- **dataframe** is a table with named columns with data, each column can has its own datatype

In [1]:
import pandas as pd

s = pd.Series([10, 20, 30], name="studietimmar")
df_demo = pd.DataFrame({
    "student": ["A", "B", "C"],
    "studietimmar": [10, 5, 8],
    "provpoäng": [85, 70, 78]
})

print(s)
print(df_demo)

0    10
1    20
2    30
Name: studietimmar, dtype: int64
  student  studietimmar  provpoäng
0       A            10         85
1       B             5         70
2       C             8         78

## load file with pd.read

In [2]:
df = pd.read_csv("files/studietimmar.csv")
print(df.head())
print(df.shape)
print(df.dtypes)

             Student Klass  Studietimmar  Provpoäng
0     Oliver Nilsson     C          14.6       56.0
1        Leo Persson     C           4.7       44.0
2  Oliver Gustafsson     A          12.4       53.0
3       Filip Olsson     D           NaN       72.0
4       Hugo Persson     C          20.6       76.0
(50, 4)
Student             str
Klass               str
Studietimmar    float64
Provpoäng       float64
dtype: object

#### Renaming the columns

In [3]:
df.columns = (df.columns    # this only affect the column names
              .str.strip()  #strips spaces from columns
              .str.replace(" ", "_")  # replaces space with _
              .str.lower()   # lower case
              )
print(df.columns)

Index(['student', 'klass', 'studietimmar', 'provpoäng'], dtype='str')

In [4]:
df.info() # shows number of values and datatypes

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student       50 non-null     str
 1   klass         50 non-null     str
 2   studietimmar  47 non-null     float64
 3   provpoäng     47 non-null     float64
dtypes: float64(2), str(2)
memory usage: 1.7 KB

In [5]:
df.describe() # show statistical keyvalues for numerical columns only

       studietimmar  provpoäng
count     47.000000  47.000000
mean      16.495745  66.382979
std        7.225437  16.849143
min        2.400000  30.000000
25%       12.100000  55.500000
50%       17.700000  71.000000
75%       21.300000  76.500000
max       29.200000  95.000000

In [6]:
df["klass"].value_counts(dropna=False)

klass
C    14
A    13
B    12
D    11
Name: count, dtype: int64

In [7]:
df[["studietimmar", "provpoäng"]].head()
mask = (df["studietimmar"] >= 5) & (df["provpoäng"] >= 70)
 # mask to filter all studietimmar below 5 and score below 70 | is used for OR
 # ~ negates the whole expression
df[mask].head()

           student klass  studietimmar  provpoäng
4     Hugo Persson     C          20.6       76.0
9    Emma Eriksson     C          29.2       90.0
10  William Olsson     A          16.5       73.0
13   Hugo Karlsson     B          21.1       71.0
16    Ebba Persson     A          24.1       84.0

- loc  
rows index, column names  
- iloc  
rows index, column index

In [8]:
print(df.loc[0:3, ["student", "studietimmar"]])
print(df.iloc[0:3, 0:2])

             student  studietimmar
0     Oliver Nilsson          14.6
1        Leo Persson           4.7
2  Oliver Gustafsson          12.4
3       Filip Olsson           NaN
             student klass
0     Oliver Nilsson     C
1        Leo Persson     C
2  Oliver Gustafsson     A

In [9]:
df.sort_values("provpoäng", ascending=False).head(3)

             student klass  studietimmar  provpoäng
48  Oliver Andersson     B          28.2       95.0
23    Noah Andersson     B          25.8       91.0
31    Wilma Eriksson     B          29.0       91.0

In [10]:
df_renamed = df.rename(columns={"provpoäng": "poäng"}) # rename a column
df_renamed.head()

             student klass  studietimmar  poäng
0     Oliver Nilsson     C          14.6   56.0
1        Leo Persson     C           4.7   44.0
2  Oliver Gustafsson     A          12.4   53.0
3       Filip Olsson     D           NaN   72.0
4       Hugo Persson     C          20.6   76.0

In [11]:
df = df.assign(poäng_per_timme = df["provpoäng"] / df["studietimmar"])
df.head()

             student klass  studietimmar  provpoäng  poäng_per_timme
0     Oliver Nilsson     C          14.6       56.0         3.835616
1        Leo Persson     C           4.7       44.0         9.361702
2  Oliver Gustafsson     A          12.4       53.0         4.274194
3       Filip Olsson     D           NaN       72.0              NaN
4       Hugo Persson     C          20.6       76.0         3.689320

In [12]:
df_drop = df.drop(columns=["poäng_per_timme"]) # removes the column
df_drop.head()

             student klass  studietimmar  provpoäng
0     Oliver Nilsson     C          14.6       56.0
1        Leo Persson     C           4.7       44.0
2  Oliver Gustafsson     A          12.4       53.0
3       Filip Olsson     D           NaN       72.0
4       Hugo Persson     C          20.6       76.0

In [13]:
print(df.isna().sum()) # how many missing values

student            0
klass              0
studietimmar       3
provpoäng          3
poäng_per_timme    5
dtype: int64

In [14]:
print(df[df["studietimmar"].isna()]) # df as a argument is because of masking directly

           student klass  studietimmar  provpoäng  poäng_per_timme
3     Filip Olsson     D           NaN       72.0              NaN
12  Noah Andersson     D           NaN        NaN              NaN
35   Leo Andersson     B           NaN       76.0              NaN

#### Data cleaning

In [15]:
df_filled = df.copy()

df_filled["studietimmar"] = df_filled["studietimmar"].fillna(0) # fills na values with 0
print(df_filled["studietimmar"].isna().sum())

0

In [16]:
df.isna().sum()
# drops rows when na appears within the choosen subsets, reset_index for recalculating indexes from 0 and up
df_clean = df.dropna(subset=["studietimmar", "provpoäng"]).reset_index(drop=True)
df_clean.head()

             student klass  studietimmar  provpoäng  poäng_per_timme
0     Oliver Nilsson     C          14.6       56.0         3.835616
1        Leo Persson     C           4.7       44.0         9.361702
2  Oliver Gustafsson     A          12.4       53.0         4.274194
3       Hugo Persson     C          20.6       76.0         3.689320
4     Olivia Persson     D          18.6       63.0         3.387097

### Analyze data

In [17]:
# for agg: new column names = (column, function)
summary = (
    df.groupby("klass")["provpoäng"]
    .agg(antal = "count", medel = "mean", median = "median", std = "std") # agg to summarize add
    .reset_index()
)
print(summary)

  klass  antal      medel  median        std
0     A     13  67.000000    73.0  15.885003
1     B     12  76.500000    78.5  14.425356
2     C     12  64.166667    62.0  14.089541
3     D     10  56.100000    60.5  18.882385

In [18]:
df.groupby("klass").agg(
    provpoäng_medel = ("provpoäng", "mean"),
    provpoäng_std = ("provpoäng", "std"),
    studietimmar_median = ("studietimmar", "median")   
).round(2).reset_index()
# new column names = (column, function)

  klass  provpoäng_medel  provpoäng_std  studietimmar_median
0     A            67.00          15.89                 19.0
1     B            76.50          14.43                 21.5
2     C            64.17          14.09                 14.7
3     D            56.10          18.88                 11.5

In [19]:
df["klass"].value_counts(normalize=True) # gives us proportions in %

klass
C    0.28
A    0.26
B    0.24
D    0.22
Name: proportion, dtype: float64

# Cleaning and summarizing data with Pandas

In [20]:
df2 = pd.read_csv("files/studietimmar.csv")

df2.columns = (df2.columns
              .str.strip()
              .str.replace(" ", "_")
              .str.lower()
              )
print(df2.head())
print()
print(df2.info())
print()
print(df2.isna().sum())
print()
print(df2.dtypes)

             student klass  studietimmar  provpoäng
0     Oliver Nilsson     C          14.6       56.0
1        Leo Persson     C           4.7       44.0
2  Oliver Gustafsson     A          12.4       53.0
3       Filip Olsson     D           NaN       72.0
4       Hugo Persson     C          20.6       76.0

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student       50 non-null     str
 1   klass         50 non-null     str
 2   studietimmar  47 non-null     float64
 3   provpoäng     47 non-null     float64
dtypes: float64(2), str(2)
memory usage: 1.7 KB
None

student         0
klass           0
studietimmar    3
provpoäng       3
dtype: int64

student             str
klass               str
studietimmar    float64
provpoäng       float64
dtype: object

#### Cleaning NA and duplicates

In [21]:
df_clean = df2.dropna(subset=["provpoäng"]) # drops na values from column
df_clean.loc[df_clean["studietimmar"].isna(), "studietimmar"] = 0 # filter column and na values and sets them to 0

print(df_clean.isna().sum())
print("Dublettrader:", df_clean.duplicated().sum()) # shows duplicates
df_clean = df_clean.drop_duplicates().reset_index(drop=True)   # drops duplicates
print("Unika Studenter:", df_clean["student"].nunique())  # shows number of unique students

student         0
klass           0
studietimmar    0
provpoäng       0
dtype: int64
Dublettrader: 0
Unika Studenter: 41

#### **Category** datatype in column

In [22]:
# sets the column variable to category, this is done to save memory, if common values like A,B,C and D
df_clean["klass"] = df_clean["klass"].astype("category")
print(df_clean.dtypes)

student              str
klass           category
studietimmar     float64
provpoäng        float64
dtype: object

#### make a new column while avoiding division by 0 with .where()

In [23]:
# makes a new column, takes where provpoäng where studietimmar > 0 (to avoid division by 0) and divides by studietimmar
# if 0 it will be set to NA
df_clean = df_clean.assign(
    poang_per_timme = df_clean["provpoäng"]
    .where(df_clean["studietimmar"] > 0, other=pd.NA) 
    / df_clean["studietimmar"]
)
print(df_clean.head())

             student klass  studietimmar  provpoäng  poang_per_timme
0     Oliver Nilsson     C          14.6       56.0         3.835616
1        Leo Persson     C           4.7       44.0         9.361702
2  Oliver Gustafsson     A          12.4       53.0         4.274194
3       Filip Olsson     D           0.0       72.0              NaN
4       Hugo Persson     C          20.6       76.0         3.689320

#### groupby summary

In [24]:
summary_klass = (df_clean
                 .groupby("klass",dropna=False)
                 .agg(
                     antal = ("student", "count"),
                      medel_poäng = ("provpoäng", "mean"),
                      median_poäng = ("provpoäng", "median"),
                      std_poäng = ("provpoäng", "std"),
                      medel_timmar = ("studietimmar", "mean")
                      ).reset_index()
                 )
print(summary_klass)

  klass  antal  medel_poäng  median_poäng  std_poäng  medel_timmar
0     A     13    67.000000          73.0  15.885003     17.230769
1     B     12    76.500000          78.5  14.425356     19.583333
2     C     12    64.166667          62.0  14.089541     16.050000
3     D     10    56.100000          60.5  18.882385     10.530000

#### crosstab with intervals from bins

In [25]:
# bins sets the intervals, normalize="index" makes it into proportion % by row (alternative to index is columns and all)
# right = True sets the right number in the interval to inclusive
bins = [0, 60, 80, 100]
proportions = pd.crosstab(
    df_clean["klass"],
    pd.cut(df_clean["provpoäng"], bins=bins, right=True),
    normalize="index"
).round(2)

print(proportions)

provpoäng  (0, 60]  (60, 80]  (80, 100]
klass
A             0.31      0.54       0.15
B             0.17      0.33       0.50
C             0.42      0.42       0.17
D             0.50      0.40       0.10

#### **assert** debugging, if values is in interval otherwise error is raised and calculating correlation

In [26]:
assert df_clean["provpoäng"].between(0, 100).all()
assert (df_clean["studietimmar"] >= 0).all()

# .corr() counts correlation value between to columns
corr = df_clean[["studietimmar", "provpoäng"]].corr().iloc[0, 1]
print("korrelation timmar-poäng", round(float(corr), 2))

korrelation timmar-poäng 0.83

## save to file with .to_csv

In [27]:
df_clean.to_csv("files/studietimmar_cleaned.csv", index=False)
summary_klass.to_csv("files/summary_by_class.csv", index=False)

### apply(), map(), replace()

In [ ]:
df['student'].apply(len) # applies a function on column no() used
df['student'].map(len) # applies a function on every variable on a dataframe, not possible for numeric
df ['student'] = df['student'].replace({'Oliver Nilsson': 'Ola Lyzerin'})
df.head()

             student klass  studietimmar  provpoäng  poäng_per_timme
0        Ola Lyzerin     C          14.6       56.0         3.835616
1        Leo Persson     C           4.7       44.0         9.361702
2  Oliver Gustafsson     A          12.4       53.0         4.274194
3       Filip Olsson     D           NaN       72.0              NaN
4       Hugo Persson     C          20.6       76.0         3.689320