# Pandas and dataframes
- **series** is a named and indexed column with data
- **dataframe** is a table with named columns with data, each column can has its own datatype

In [1]:
import pandas as pd

s = pd.Series([10, 20, 30], name="studietimmar")
df_demo = pd.DataFrame({
    "student": ["A", "B", "C"],
    "studietimmar": [10, 5, 8],
    "provpoäng": [85, 70, 78]
})

print(s)
print(df_demo)

0    10
1    20
2    30
Name: studietimmar, dtype: int64
  student  studietimmar  provpoäng
0       A            10         85
1       B             5         70
2       C             8         78

## pd.read

In [2]:
df = pd.read_csv("files/studietimmar.csv")
print(df.head())
print(df.shape)
print(df.dtypes)

             Student Klass  Studietimmar  Provpoäng
0     Oliver Nilsson     C          14.6       56.0
1        Leo Persson     C           4.7       44.0
2  Oliver Gustafsson     A          12.4       53.0
3       Filip Olsson     D           NaN       72.0
4       Hugo Persson     C          20.6       76.0
(50, 4)
Student             str
Klass               str
Studietimmar    float64
Provpoäng       float64
dtype: object

In [3]:
df.columns = (df.columns    # this only affect the column names
              .str.strip() #strips spaces from columns
              .str.replace(" ", "_") # replaces space with _
              .str.lower() # lower case
              )
print(df.columns)

Index(['student', 'klass', 'studietimmar', 'provpoäng'], dtype='str')

In [4]:
df.info() # shows missing values and datatypes

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   student       50 non-null     str
 1   klass         50 non-null     str
 2   studietimmar  47 non-null     float64
 3   provpoäng     47 non-null     float64
dtypes: float64(2), str(2)
memory usage: 1.7 KB

In [5]:
df.describe() # show statistical keyvalues for numerical columns only

       studietimmar  provpoäng
count     47.000000  47.000000
mean      16.495745  66.382979
std        7.225437  16.849143
min        2.400000  30.000000
25%       12.100000  55.500000
50%       17.700000  71.000000
75%       21.300000  76.500000
max       29.200000  95.000000

In [7]:
df["klass"].value_counts(dropna=False)

klass
C    14
A    13
B    12
D    11
Name: count, dtype: int64

In [ ]:
df[["studietimmar", "provpoäng"]].head()
mask = (df["studietimmar"] >= 5) & (df["provpoäng"] >= 70)
 # mask to filter all studietimmar below 5 and score below 70 | is used for OR
 # ~ negates the whole expression
df[mask].head()

           student klass  studietimmar  provpoäng
4     Hugo Persson     C          20.6       76.0
9    Emma Eriksson     C          29.2       90.0
10  William Olsson     A          16.5       73.0
13   Hugo Karlsson     B          21.1       71.0
16    Ebba Persson     A          24.1       84.0

- loc  
rows index, column names  
- iloc  
rows index, column index

In [17]:
print(df.loc[0:3, ["student", "studietimmar"]])
print(df.iloc[0:3, 0:2])

             student  studietimmar
0     Oliver Nilsson          14.6
1        Leo Persson           4.7
2  Oliver Gustafsson          12.4
3       Filip Olsson           NaN
             student klass
0     Oliver Nilsson     C
1        Leo Persson     C
2  Oliver Gustafsson     A

In [19]:
df.sort_values("provpoäng", ascending=False).head(3)

             student klass  studietimmar  provpoäng
48  Oliver Andersson     B          28.2       95.0
23    Noah Andersson     B          25.8       91.0
31    Wilma Eriksson     B          29.0       91.0

In [ ]:
df_renamed = df.rename(columns={"provpoäng": "poäng"}) # rename a column
df_renamed.head()

             student klass  studietimmar  poäng
0     Oliver Nilsson     C          14.6   56.0
1        Leo Persson     C           4.7   44.0
2  Oliver Gustafsson     A          12.4   53.0
3       Filip Olsson     D           NaN   72.0
4       Hugo Persson     C          20.6   76.0

In [25]:
df = df.assign(poäng_per_timme = df["provpoäng"] / df["studietimmar"])
df.head()

             student klass  studietimmar  provpoäng  poäng_per_timme
0     Oliver Nilsson     C          14.6       56.0         3.835616
1        Leo Persson     C           4.7       44.0         9.361702
2  Oliver Gustafsson     A          12.4       53.0         4.274194
3       Filip Olsson     D           NaN       72.0              NaN
4       Hugo Persson     C          20.6       76.0         3.689320

In [ ]:
df_drop = df.drop(columns=["poäng_per_timme"]) # removes the column
df_drop.head()

             student klass  studietimmar  provpoäng
0     Oliver Nilsson     C          14.6       56.0
1        Leo Persson     C           4.7       44.0
2  Oliver Gustafsson     A          12.4       53.0
3       Filip Olsson     D           NaN       72.0
4       Hugo Persson     C          20.6       76.0